Repository sockify/sockify, pull requests merged in 2024-10, with the labels that each got.

#52 GET /orders?status="" to list orders
  api/cmd/migrate/migrations/20240915231453_add_order_id_index.up.sql
  api/docs/docs.go
  api/docs/swagger.json
  api/docs/swagger.yaml
  api/routes/routes.go
  api/services/orders/order_handler.go
  api/services/orders/order_store.go
  api/types/entities.go
  api/types/payloads.go
  api/types/stores.go
Labels: backend

#53 PATCH /orders/:order_id/address to update an order's address
  api/docs/docs.go
  api/docs/swagger.json
  api/docs/swagger.yaml
  api/middleware/auth.go
  api/services/orders/order_handler.go
  api/services/orders/order_store.go
  api/types/entities.go
  api/types/payloads.go
  api/types/stores.go
Labels: backend

#54 feat: adds the PATCH /orders/:id/status endpoint
  api/cmd/migrate/migrations/20240915230043_add_orders_table.up.sql
  api/docs/docs.go
  api/docs/swagger.json
  api/docs/swagger.yaml
  api/services/orders/order_handler.go
  api/services/orders/order_store.go
  api/types/payloads.go
  api/types/stores.go
Labels: backend

#55 feat: adds GET /orders/:id/updates endpoint
  api/docs/docs.go
  api/docs/swagger.json
  api/docs/swagger.yaml
  api/services/orders/order_handler.go
  api/services/orders/order_store.go
  api/types/entities.go
  api/types/stores.go
Labels: backend

#58 Create GET /orders/invoice/:invoice_number to view order details and item list
  api/docs/docs.go
  api/docs/swagger.json
  api/docs/swagger.yaml
  api/services/orders/order_handler.go
  api/services/orders/order_store.go
  api/types/entities.go
  api/types/stores.go
Labels: backend

#59 docs: adds main UI mocks for user and admin experiences
  docs/assets/ui_mocks_add_item_step_1.png
  docs/assets/ui_mocks_add_item_step_2.png
  docs/assets/ui_mocks_add_item_step_3.png
  docs/assets/ui_mocks_add_order_update.png
  docs/assets/ui_mocks_admin_login.png
  docs/assets/ui_mocks_cart.png
  docs/assets/ui_mocks_checkout.png
  docs/assets/ui_mocks_edit_product.png
  docs/assets/ui_mocks_footer.png
  docs/assets/ui_mocks_inventory_admin_item.png
  docs/assets/ui_mocks_inventory_item_details.png
  docs/assets/ui_mocks_inventory_management.png
  docs/assets/ui_mocks_inventory_page.png
  docs/assets/ui_mocks_inventory_sidebar.png
  docs/assets/ui_mocks_order.png
  docs/assets/ui_mocks_order_confirmation.png
  docs/assets/ui_mocks_orders_view.png
  docs/planning/ui_mocks.md
Labels: docs, frontend

#61 feat: adds the `POST /orders/:id/update` endpoint to create new order…
  api/docs/docs.go
  api/docs/swagger.json
  api/docs/swagger.yaml
  api/services/orders/order_handler.go
  api/services/orders/order_store.go
  api/types/payloads.go
  api/types/stores.go
Labels: backend

#63 feat: add core UI routes and auth flow
  api/services/admin/handler.go
  web-client/package-lock.json
  web-client/package.json
  web-client/src/api/admins/model.ts
  web-client/src/api/admins/queries.ts
  web-client/src/api/admins/service.ts
  web-client/src/components/AuthProtectedRoutes.tsx
  web-client/src/components/NotFound.tsx
  web-client/src/context/AuthContext.tsx
  web-client/src/layouts/AdminLayout.tsx
  web-client/src/layouts/RootLayout.tsx
  web-client/src/main.tsx
  web-client/src/pages/HomePage.tsx
  web-client/src/pages/admin/AdminHomePage.tsx
  web-client/src/pages/admin/AdminLoginPage.tsx
  web-client/src/shared/axios.ts
  web-client/src/shared/constants.ts
  web-client/src/shared/utils/jwt.ts
Labels: frontend

#66 feat: adds the GET /orders/:order_id endpoint
  api/docs/docs.go
  api/docs/swagger.json
  api/docs/swagger.yaml
  api/services/orders/order_handler.go
  api/services/orders/order_store.go
  api/types/stores.go
Labels: backend

#64 Sock update
  api/docs/docs.go
  api/docs/swagger.json
  api/docs/swagger.yaml
  api/services/inventory/sock_handler.go
  api/services/inventory/sock_store.go
  api/types/entities.go
  api/types/payloads.go
  api/types/stores.go
  web-client/package-lock.json
  web-client/package.json
Labels: backend

#68 feat: adds `GET /admin/:admin_id` endpoint and updates UI
  api/docs/docs.go
  api/docs/swagger.json
  api/docs/swagger.yaml
  api/middleware/auth.go
  api/services/admin/handler.go
  api/services/admin/store.go
  web-client/src/api/admins/model.ts
  web-client/src/api/admins/queries.ts
  web-client/src/api/admins/service.ts
  web-client/src/components/AuthProtectedRoutes.tsx
  web-client/src/components/LoadingSpinner.tsx
  web-client/src/components/NotFound.tsx
  web-client/src/context/AuthContext.tsx
  web-client/src/main.tsx
  web-client/src/pages/admin/AdminLoginPage.tsx
  web-client/src/shared/utils/jwt.ts
Labels: frontend, backend

#71 feat: adds admin login page UI
  web-client/package-lock.json
  web-client/package.json
  web-client/src/api/admins/queries.ts
  web-client/src/components/LoadingSpinner.tsx
  web-client/src/components/ui/button.tsx
  web-client/src/components/ui/card.tsx
  web-client/src/components/ui/form.tsx
  web-client/src/components/ui/input.tsx
  web-client/src/components/ui/label.tsx
  web-client/src/components/ui/separator.tsx
  web-client/src/context/AuthContext.tsx
  web-client/src/pages/admin/AdminLoginPage.tsx
Labels: frontend

#73 feat: add navbar Ui for admins and users
  web-client/package-lock.json
  web-client/package.json
  web-client/src/components/AdminNavbar.tsx
  web-client/src/components/AuthProtectedRoutes.tsx
  web-client/src/components/LoadingSpinner.tsx
  web-client/src/components/NavLink.tsx
  web-client/src/components/Navbar.tsx
  web-client/src/components/NotFound.tsx
  web-client/src/components/ui/dropdown-menu.tsx
  web-client/src/components/ui/tooltip.tsx
  web-client/src/index.css
  web-client/src/layouts/AdminLayout.tsx
  web-client/src/layouts/RootLayout.tsx
  web-client/src/main.tsx
  web-client/src/pages/admin/AdminInventoryPage.tsx
  web-client/src/pages/admin/AdminLoginPage.tsx
  web-client/src/shared/constants.ts
Labels: frontend

#75 feat: adds the admin and user footers to the UI
  web-client/src/components/AdminFooter.tsx
  web-client/src/components/Footer.tsx
  web-client/src/context/AuthContext.tsx
  web-client/src/layouts/AdminLayout.tsx
  web-client/src/layouts/RootLayout.tsx
  web-client/src/pages/admin/AdminLoginPage.tsx
Labels: frontend

#77 feat: admins table UI to profile page
  web-client/src/components/AdminNavbar.tsx
  web-client/src/components/AdminProfile.tsx
  web-client/src/components/AdminsTable.tsx
  web-client/src/components/TableEmpty.tsx
  web-client/src/components/TableNoResults.tsx
  web-client/src/components/ui/avatar.tsx
  web-client/src/components/ui/badge.tsx
  web-client/src/components/ui/button.tsx
  web-client/src/components/ui/card.tsx
  web-client/src/components/ui/dropdown-menu.tsx
  web-client/src/components/ui/form.tsx
  web-client/src/components/ui/input.tsx
  web-client/src/components/ui/label.tsx
  web-client/src/components/ui/pagination.tsx
  web-client/src/components/ui/separator.tsx
  web-client/src/components/ui/skeleton.tsx
  web-client/src/components/ui/table.tsx
  web-client/src/components/ui/tooltip.tsx
  web-client/src/context/AuthContext.tsx
  web-client/src/index.css
  web-client/src/main.tsx
  web-client/src/pages/admin/AdminLoginPage.tsx
  web-client/src/pages/admin/AdminProfilePage.tsx
Labels: frontend

#92 feat: adds Stripe checkout endpoints
  README.md
  api/Dockerfile
  api/cmd/main.go
  api/cmd/migrate/migrations/20240915225821_add_order_status_enum.up.sql
  api/cmd/migrate/migrations/20240915230043_add_orders_table.up.sql
  api/config/env.go
  api/docs/docs.go
  api/docs/swagger.json
  api/docs/swagger.yaml
  api/go.mod
  api/go.sum
  api/routes/routes.go
  api/services/admin/store.go
  api/services/cart/handler.go
  api/services/cart/service.go
  api/services/inventory/sock_store.go
  api/services/orders/order_handler.go
  api/services/orders/order_store.go
  api/types/entities.go
  api/types/payloads.go
  api/types/stores.go
  api/utils/helpers.go
  docs/assets/payment_processing_flow.png
  docs/planning/database_schema.md
  docs/planning/entity_relationship_diagram.md
  docs/planning/payment_processing.md
Labels: backend

#93 feat: adds a basic payment canceled page to the UI
  web-client/src/main.tsx
  web-client/src/pages/PaymentCanceledPage.tsx
Labels: frontend

#95 feat: adds order confirmation ui
  web-client/src/api/admins/queries.ts
  web-client/src/api/cart/model.ts
  web-client/src/api/cart/queries.ts
  web-client/src/api/cart/service.ts
  web-client/src/api/orders/model.ts
  web-client/src/api/orders/queries.ts
  web-client/src/api/orders/service.ts
  web-client/src/components/GenericError.tsx
  web-client/src/components/dev/CartDemo.tsx
  web-client/src/context/CartContext.tsx
  web-client/src/main.tsx
  web-client/src/pages/OrderConfirmationPage.tsx
  web-client/src/pages/PaymentCanceledPage.tsx
  web-client/src/shared/constants.ts
  web-client/src/shared/utils/strings.ts
Labels: frontend

#100 feat: adds admins order UI
  api/services/orders/order_handler.go
  api/services/orders/order_store.go
  api/types/stores.go
  web-client/package-lock.json
  web-client/package.json
  web-client/src/api/orders/queries.ts
  web-client/src/api/orders/service.ts
  web-client/src/components/OrdersTable.tsx
  web-client/src/components/TextInputWithDropdown.tsx
  web-client/src/components/ui/select.tsx
  web-client/src/pages/admin/AdminOrdersPage.tsx
Labels: frontend, backend

#103 Order details UI
  api/cmd/migrate/migrations/20240915230043_add_orders_table.up.sql
  web-client/package-lock.json
  web-client/package.json
  web-client/src/api/orders/model.ts
  web-client/src/api/orders/queries.ts
  web-client/src/api/orders/service.ts
  web-client/src/components/TableEmpty.tsx
  web-client/src/components/ui/dialog.tsx
  web-client/src/components/ui/textarea.tsx
  web-client/src/main.tsx
  web-client/src/pages/admin/AdminOrderDetailsPage.tsx
  web-client/src/pages/admin/AdminOrdersPage.tsx
  web-client/src/shared/constants.ts
  web-client/src/shared/types.ts
Labels: frontend

#106 Create the CheckoutPage
  web-client/src/main.tsx
  web-client/src/pages/CheckoutPage.tsx
Labels: frontend

#108 feat: UI cleanup and connecting flow through checkout and pay
  web-client/src/api/cart/model.ts
  web-client/src/api/cart/queries.ts
  web-client/src/api/cart/service.ts
  web-client/src/api/inventory/model.ts
  web-client/src/api/inventory/queries.ts
  web-client/src/api/inventory/service.ts
  web-client/src/api/orders/model.ts
  web-client/src/api/socks/model.ts
  web-client/src/api/socks/service.ts
  web-client/src/components/CartItem.tsx
  web-client/src/components/OrdersTable.tsx
  web-client/src/main.tsx
  web-client/src/pages/CartPage.tsx
  web-client/src/pages/CheckoutPage.tsx
  web-client/src/pages/SockDetailsPage.tsx
  web-client/src/pages/socks/SockDetailsPage.tsx
Labels: frontend, backend
