Repository sockify/sockify, pull requests merged in 2024-11, with the labels that each got.

#115 feat: sock item home page
  .gitignore
  web-client/src/api/inventory/model.ts
  web-client/src/api/inventory/queries.ts
  web-client/src/api/inventory/service.ts
  web-client/src/components/SockCard.tsx
  web-client/src/pages/CartPage.tsx
  web-client/src/pages/CheckoutPage.tsx
  web-client/src/pages/HomePage.tsx
  web-client/src/pages/SockDetailsPage.tsx
Labels: frontend, backend

#116 Similar items
  api/docs/docs.go
  api/docs/swagger.json
  api/docs/swagger.yaml
  api/services/inventory/sock_handler.go
  api/services/inventory/sock_store.go
  api/types/entities.go
  api/types/stores.go
  web-client/src/api/inventory/model.ts
  web-client/src/api/inventory/queries.ts
  web-client/src/api/inventory/service.ts
  web-client/src/pages/SockDetailsPage.tsx
Labels: frontend, backend

#117 feat: adds the newsletter API endpoint and integrates them within the UI
  api/cmd/migrate/migrations/20241106183418_add_newsletter_table.down.sql
  api/cmd/migrate/migrations/20241106183418_add_newsletter_table.up.sql
  api/cmd/migrate/migrations/20241106183709_add_newsletter_email_index.down.sql
  api/cmd/migrate/migrations/20241106183709_add_newsletter_email_index.up.sql
  api/docs/docs.go
  api/docs/swagger.json
  api/docs/swagger.yaml
  api/routes/routes.go
  api/services/newsletter/handler.go
  api/services/newsletter/store.go
  api/types/entities.go
  api/types/payloads.go
  api/types/stores.go
  web-client/src/api/newsletter/model.ts
  web-client/src/api/newsletter/queries.ts
  web-client/src/api/newsletter/service.ts
  web-client/src/components/Footer.tsx
Labels: frontend, backend

#118 feat: integrates the `Send Grid` email client to send order confirmations
  README.md
  api/config/env.go
  api/go.mod
  api/go.sum
  api/routes/routes.go
  api/services/cart/handler.go
  api/services/email/service.go
  api/services/email/templates/order_confirmation.go
  api/utils/constants.go
Labels: backend

#122 Add new socks
  api/types/payloads.go
  web-client/src/api/inventory/model.ts
  web-client/src/api/inventory/queries.ts
  web-client/src/api/inventory/service.ts
  web-client/src/components/AddSockForm.tsx
  web-client/src/components/AddSockModal.tsx
  web-client/src/components/dev/AddSockModalDemo.tsx
  web-client/src/main.tsx
  web-client/src/pages/admin/AdminInventoryPage.tsx
Labels: frontend

#125 feat: adds dark mode toggle
  web-client/src/components/AdminNavbar.tsx
  web-client/src/components/Navbar.tsx
  web-client/src/components/ui/theme-toggle-button.tsx
  web-client/src/context/ThemeContext.tsx
  web-client/src/main.tsx
  web-client/src/pages/admin/AdminInventoryPage.tsx
  web-client/src/pages/admin/AdminLoginPage.tsx
Labels: frontend

#126 Admin sock details
  docs/planning/user_stories.md
  web-client/src/api/inventory/model.ts
  web-client/src/api/inventory/queries.ts
  web-client/src/api/inventory/service.ts
  web-client/src/components/AddSizeModal.tsx
  web-client/src/components/EditItemModal.tsx
  web-client/src/components/EditVariantModal.tsx
  web-client/src/components/SockCard.tsx
  web-client/src/main.tsx
  web-client/src/pages/admin/AdminInventoryPage.tsx
  web-client/src/pages/admin/AdminSockDetailsPage.tsx
Labels: frontend

#131 feat: add city column and update the UI
  api/cmd/migrate/migrations/20240915230043_add_orders_table.up.sql
  api/docs/docs.go
  api/docs/swagger.json
  api/docs/swagger.yaml
  api/services/email/templates/order_confirmation.go
  api/services/orders/order_store.go
  api/types/entities.go
  api/types/payloads.go
  docs/planning/database_schema.md
  docs/planning/entity_relationship_diagram.md
  docs/planning/payment_processing.md
  web-client/src/api/orders/model.ts
  web-client/src/pages/CheckoutPage.tsx
  web-client/src/pages/admin/AdminOrderDetailsPage.tsx
  web-client/src/shared/constants.ts
  web-client/src/shared/utils/strings.ts
Labels: bug, docs, frontend, backend
